#!/bin/sh
#
# Pre-commit hook to run linting and prettier before every commit

# Run the lint and prettier targets
nx run-many --targets=lint,prettier-check --projects=medical-models

# Capture the exit code of the linting and prettier process
if [ $? -ne 0 ]; then
    echo "Linting or prettier failed. Commit aborted."
    exit 1
fi

# If linting passes, allow the commit
exit 0
